site_name: PyScrum
site_description: Minimalist Scrum tool for developers
site_author: dospalko
theme:
  name: material

nav:
  - Home: index.md
  - CLI Usage: cli.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - meta
  - def_list
